export const trigrams = [
  {
    number: 1,
    names: ['Force', 'The Creative'],
    chineseName: '乾',
    pinyinName: 'qián',
    character: '☰',
    attribute: 'strong',
    images: ['heaven'],
    chineseImage: '天',
    pinyinImage: 'tiān',
    familyRelationship: 'father',
    binary: '111',
    lines: [1, 1, 1],
  },
  {
    number: 2,
    names: ['Field', 'The Receptive'],
    chineseName: '坤',
    pinyinName: 'kūn',
    character: '☷',
    attribute: 'devoted, yielding',
    images: ['earth'],
    chineseImage: '地',
    pinyinImage: 'dì',
    familyRelationship: 'mother',
    binary: '000',
    lines: [0, 0, 0],
  },
  {
    number: 3,
    names: ['Shake', 'The Arousing'],
    chineseName: '震',
    pinyinName: 'zhèn',
    character: '☳',
    attribute: 'inciting movement',
    images: ['thunder'],
    chineseImage: '雷',
    pinyinImage: 'léi',
    familyRelationship: 'first son',
    binary: '001',
    lines: [1, 0, 0],
  },
  {
    number: 4,
    names: ['Gorge', 'The Abysmal'],
    chineseName: '坎',
    pinyinName: 'kǎn',
    character: '☵',
    attribute: 'dangerous',
    images: ['water'],
    chineseImage: '水',
    pinyinImage: 'shuǐ',
    familyRelationship: 'second son',
    binary: '010',
    lines: [0, 1, 0],
  },
  {
    number: 5,
    names: ['Bound', 'Keeping Still'],
    chineseName: '艮',
    pinyinName: 'gèn',
    character: '☶',
    attribute: 'resting',
    images: ['mountain'],
    chineseImage: '山',
    pinyinImage: 'shān',
    familyRelationship: 'third son',
    binary: '100',
    lines: [0, 0, 1],
  },
  {
    number: 6,
    names: ['Ground', 'The Gentle'],
    chineseName: '巽',
    pinyinName: 'xùn',
    character: '☴',
    attribute: 'penetrating',
    images: ['wind', 'wood'],
    chineseImage: '風',
    pinyinImage: 'fēng',
    familyRelationship: 'first daughter',
    binary: '110',
    lines: [0, 1, 1],
  },
  {
    number: 7,
    names: ['Radiance', 'The Clinging'],
    chineseName: '離',
    pinyinName: 'lí',
    character: '☲',
    attribute: 'light-giving',
    images: ['fire'],
    chineseImage: '火',
    pinyinImage: 'huǒ',
    familyRelationship: 'second daughter',
    binary: '101',
    lines: [1, 0, 1],
  },
  {
    number: 8,
    names: ['Open', 'The Joyous'],
    chineseName: '兌',
    pinyinName: 'duì',
    character: '☱',
    attribute: 'joyful',
    images: ['swamp', 'lake'],
    chineseImage: '澤',
    pinyinImage: 'zé',
    familyRelationship: 'third daughter',
    binary: '011',
    lines: [1, 1, 0],
  },
];
export const hexagrams = [
  {
    number: 1,
    names: ['Force', 'The Creative'],
    chineseName: '乾',
    pinyinName: 'qián',
    character: '䷀',
    topTrigram: 1,
    bottomTrigram: 1,
    binary: '111111',
    linesString: '111111',
    lines: [1, 1, 1, 1, 1, 1],
    description:
      'Heaven above and Heaven below: Heaven in constant motion. With the strength of the dragon, the Superior Person steels herself for ceaseless activity. Productive activity. Potent Influence. Sublime success if you keep to your course.',
  },
  {
    number: 2,
    names: ['Field', 'The Receptive'],
    chineseName: '坤',
    pinyinName: 'kūn',
    character: '䷁',
    topTrigram: 2,
    bottomTrigram: 2,
    binary: '000000',
    linesString: '000000',
    lines: [0, 0, 0, 0, 0, 0],
    description:
      'Earth above and Earth below: The Earth contains and sustains. In this situation, The Superior Person should not take the initiative; she should follow the initiative of another. She should seek receptive allies in the southwest; she should break ties with immovable allies in the northeast. Responsive devotion. Receptive influence. Sublime success if you keep to your course.',
  },
  {
    number: 3,
    names: ['Sprouting', 'Difficulty at the Beginning'],
    chineseName: '屯',
    pinyinName: 'zhūn',
    character: '䷂',
    topTrigram: 4,
    bottomTrigram: 3,
    binary: '010001',
    linesString: '100010',
    lines: [1, 0, 0, 0, 1, 0],
    description:
      'Thunder from the Deep: The Superior Person carefully weaves order out of confusion. Supreme success if you keep to your course. Carefully consider the first move. Seek help.',
  },
  {
    number: 4,
    names: ['Enveloping', 'Youthful Folly'],
    chineseName: '蒙',
    pinyinName: 'méng',
    character: '䷃',
    topTrigram: 5,
    bottomTrigram: 4,
    binary: '100010',
    linesString: '010001',
    lines: [0, 1, 0, 0, 0, 1],
    description:
      'A fresh Spring at the foot of the Mountain: The Superior Person refines her character by being thorough in every activity. The sage does not recruit students; the students seek her. She asks nothing but a sincere desire to learn. If the student doubts or challenges her authority, the sage regretfully cuts her losses. Success if you are sincerely firm.',
  },
  {
    number: 5,
    names: ['Attending', 'Waiting'],
    chineseName: '需',
    pinyinName: 'xū',
    character: '䷄',
    topTrigram: 4,
    bottomTrigram: 1,
    binary: '010111',
    linesString: '111010',
    lines: [1, 1, 1, 0, 1, 0],
    description:
      'Deep Waters in the Heavens: Thunderclouds approaching from the west, but no rain yet. The Superior Person nourishes herself and remains of good cheer to condition herself for the moment of truth. Great success if you sincerely keep to your course. You may cross to the far shore.',
  },
  {
    number: 6,
    names: ['Arguing', 'Conflict'],
    chineseName: '訟',
    pinyinName: 'sòng',
    character: '䷅',
    topTrigram: 1,
    bottomTrigram: 4,
    binary: '111010',
    linesString: '010111',
    lines: [0, 1, 0, 1, 1, 1],
    description:
      'The high Heavens over a yawning Deep chasm: an expansive void where nothing can dwell. Even though she sincerely knows she is right, the Superior Person anticipates opposition and carefully prepares for any incident. Good fortune if your conflict results in compromise. Misfortune if your conflict escalates to confrontation. Seek advice. Postpone your crossing to the far shore.',
  },
  {
    number: 7,
    names: ['Leading', 'The Army'],
    chineseName: '師',
    pinyinName: 'shī',
    character: '䷆',
    topTrigram: 2,
    bottomTrigram: 4,
    binary: '000010',
    linesString: '010000',
    lines: [0, 1, 0, 0, 0, 0],
    description:
      "Deep Water beneath the Earth's surface: Untapped resources are available. The Superior Person nourishes and instructs the people, building a loyal, disciplined following. Good fortune. No mistakes if you follow a course led by experience.",
  },
  {
    number: 8,
    names: ['Grouping', 'Holding Together [Union]'],
    chineseName: '比',
    pinyinName: 'bǐ',
    character: '䷇',
    topTrigram: 4,
    bottomTrigram: 2,
    binary: '010000',
    linesString: '000010',
    lines: [0, 0, 0, 0, 1, 0],
    description:
      'Deep waters on the face of the Earth: Surface Waters flow together. The Superior Person recognizes the situation calls for joining together. Thus she cultivates friendly relations with all. Good fortune is possible. Cast the coins again to discover if you have the qualities needed to lead such a group. Then there will be no error. Those uncertain will gradually join. Those who join too late will meet with misfortune.',
  },
  {
    number: 9,
    names: ['Small Accumulating', 'The Taming Power of the Small'],
    chineseName: '小畜',
    pinyinName: 'xiǎo chù',
    character: '䷈',
    topTrigram: 6,
    bottomTrigram: 1,
    binary: '110111',
    linesString: '111011',
    lines: [1, 1, 1, 0, 1, 1],
    description:
      'Winds of change high in the Heavens: Air currents carry the weather. Dense clouds blow in from the west, but still no rain. The Superior Person fine tunes the image she presents to the world. Small successes.',
  },
  {
    number: 10,
    names: ['Treading', 'Conduct'],
    chineseName: '履',
    pinyinName: 'lǚ',
    character: '䷉',
    topTrigram: 1,
    bottomTrigram: 8,
    binary: '111011',
    linesString: '110111',
    lines: [1, 1, 0, 1, 1, 1],
    description:
      'Heaven shines down on the Marsh which reflects it back imperfectly: Though the Superior Person carefully discriminates between high and low, and acts in accord with the flow of the Tao, there are still situations where a risk must be taken. You tread upon the tail of the tiger. Not perceiving you as a threat, the startled tiger does not bite. Success.',
  },
  {
    number: 11,
    names: ['Pervading', 'Peace'],
    chineseName: '泰',
    pinyinName: 'tài',
    character: '䷊',
    topTrigram: 2,
    bottomTrigram: 1,
    binary: '000111',
    linesString: '111000',
    lines: [1, 1, 1, 0, 0, 0],
    description:
      'Heaven and Earth embrace, giving birth to Peace. The Superior Person serves as midwife, presenting the newborn gift to the people. The small depart; the great approach. Success. Good fortune.',
  },
  {
    number: 12,
    names: ['Obstruction', 'Standstill (Stagnation)'],
    chineseName: '否',
    pinyinName: 'pǐ',
    character: '䷋',
    topTrigram: 1,
    bottomTrigram: 2,
    binary: '111000',
    linesString: '000111',
    lines: [0, 0, 0, 1, 1, 1],
    description:
      'Heaven and Earth move away from each other. In the ensuing void, the small invade where the great have departed. There is no common meeting ground, so the Superior Person must fall back on her inner worth and decline the rewards offered by the inferior invaders. Difficult trials as you hold to your course.',
  },
  {
    number: 13,
    names: ['Concording People', 'Fellowship with Men'],
    chineseName: '同人',
    pinyinName: 'tóng rén',
    character: '䷌',
    topTrigram: 1,
    bottomTrigram: 7,
    binary: '111101',
    linesString: '101111',
    lines: [1, 0, 1, 1, 1, 1],
    description:
      'Heaven reflects the Flame of clarity: The Superior Person analyzes the various levels and working parts of the social structure, and uses them to advantage. Success if you keep to your course. You may cross to the far shore.',
  },
  {
    number: 14,
    names: ['Great Possessing', 'Possession in Great Measure'],
    chineseName: '大有',
    pinyinName: 'dà yǒu',
    character: '䷍',
    topTrigram: 7,
    bottomTrigram: 1,
    binary: '101111',
    linesString: '111101',
    lines: [1, 1, 1, 1, 0, 1],
    description:
      'The Fire of clarity illuminates the Heavens to those below: The Superior Person possesses great inner treasures -- compassion, economy, and modesty. These treasures allow the benevolent will of Heaven to flow through her outward to curb evil and further good. Supreme success.',
  },
  {
    number: 15,
    names: ['Humbling', 'Modesty'],
    chineseName: '謙',
    pinyinName: 'qiān',
    character: '䷎',
    topTrigram: 2,
    bottomTrigram: 5,
    binary: '000100',
    linesString: '001000',
    lines: [0, 0, 1, 0, 0, 0],
    description:
      'The Mountain does not overshadow the Plain surrounding it: Such modest consideration in a Superior Person creates a channel through which excess flows to the needy. Success if you carry things through.',
  },
  {
    number: 16,
    names: ['Providing-For', 'Enthusiasm'],
    chineseName: '豫',
    pinyinName: 'yù',
    character: '䷏',
    topTrigram: 3,
    bottomTrigram: 2,
    binary: '001000',
    linesString: '000100',
    lines: [0, 0, 0, 1, 0, 0],
    description:
      'Thunder comes resounding out of the Earth: Similar thunder roars up from the masses when the Superior Person strikes a chord in their hearts. Whip up enthusiasm, rally your forces, and move boldly forward.',
  },
  {
    number: 17,
    names: ['Following'],
    chineseName: '隨',
    pinyinName: 'suí',
    character: '䷐',
    topTrigram: 8,
    bottomTrigram: 3,
    binary: '011001',
    linesString: '100110',
    lines: [1, 0, 0, 1, 1, 0],
    description:
      "Thunder beneath the Lake's surface. The Superior Person allows herself plenty of sheltered rest and recuperation while awaiting a clear sign to follow. Supreme success. No mistakes if you keep to your course.",
  },
  {
    number: 18,
    names: ['Correcting', 'Work on What Has Been Spoiled [Decay]'],
    chineseName: '蠱',
    pinyinName: 'gǔ',
    character: '䷑',
    topTrigram: 5,
    bottomTrigram: 6,
    binary: '100110',
    linesString: '011001',
    lines: [0, 1, 1, 0, 0, 1],
    description:
      'Winds sweep through the Mountain valley: The Superior Person sweeps away corruption and stagnation by stirring up the people and strengthening their spirit. Supreme success. Before crossing to the far shore, consider the move for three days. After crossing, devote three days of hard labor to damage control.',
  },
  {
    number: 19,
    names: ['Nearing', 'Approach'],
    chineseName: '臨',
    pinyinName: 'lín',
    character: '䷒',
    topTrigram: 2,
    bottomTrigram: 8,
    binary: '000011',
    linesString: '110000',
    lines: [1, 1, 0, 0, 0, 0],
    description:
      'The rich, loamy Earth on the banks of the Marsh provides fertile soil for exceptional progress. The Superior Person is inexhaustible in her willingness to teach, and without limit in her tolerance and support of others. Supreme success if you keep to your course. But be aware that your time is limited; Your power will wane, as Summer changes to Fall.',
  },
  {
    number: 20,
    names: ['Viewing', 'Contemplation (View)'],
    chineseName: '觀',
    pinyinName: 'guān',
    character: '䷓',
    topTrigram: 6,
    bottomTrigram: 2,
    binary: '110000',
    linesString: '000011',
    lines: [0, 0, 0, 0, 1, 1],
    description:
      'The gentle Wind roams the Earth: The Superior Person expands her sphere of influence as she expands her awareness. Deeply devoted to her pursuit of clarity and wisdom, she is unconscious of the inspiring, positive example she is setting for others to emulate. You have cleansed yourself; now stand ready to make your humble, devout offering.',
  },
  {
    number: 21,
    names: ['Gnawing Bite', 'Biting Through'],
    chineseName: '噬嗑',
    pinyinName: 'shì kè',
    character: '䷔',
    topTrigram: 7,
    bottomTrigram: 3,
    binary: '101001',
    linesString: '100101',
    lines: [1, 0, 0, 1, 0, 1],
    description:
      'The merciless, searing judgement of Lightning fulfills the warning prophecies of distant Thunder. Sage rulers preserved justice by clearly defining the laws, and by delivering the penalties decreed. Though unpleasant, it is best to let justice have its due.',
  },
  {
    number: 22,
    names: ['Adorning', 'Grace'],
    chineseName: '賁',
    pinyinName: 'bì',
    character: '䷕',
    topTrigram: 5,
    bottomTrigram: 7,
    binary: '100101',
    linesString: '101001',
    lines: [1, 0, 1, 0, 0, 1],
    description:
      "Fire illuminates the base of the Mountain: The Superior Person realizes she has not the wisdom to move the course of the world, except by attending to each day's affairs as they come. Success in small matters. This is a good time to begin something.",
  },
  {
    number: 23,
    names: ['Stripping', 'Splitting Apart'],
    chineseName: '剝',
    pinyinName: 'bō',
    character: '䷖',
    topTrigram: 5,
    bottomTrigram: 2,
    binary: '100000',
    linesString: '000001',
    lines: [0, 0, 0, 0, 0, 1],
    description:
      'The weight of the Mountain presses down upon a weak foundation of Earth: The Superior Person will use this time of oppression to attend to the needs of those less fortunate. Any action would be ill-timed. Stand fast.',
  },
  {
    number: 24,
    names: ['Returning', 'Return (The Turning Point)'],
    chineseName: '復',
    pinyinName: 'fù',
    character: '䷗',
    topTrigram: 2,
    bottomTrigram: 3,
    binary: '000001',
    linesString: '100000',
    lines: [1, 0, 0, 0, 0, 0],
    description:
      "Thunder regenerates deep within Earth's womb: Sage rulers recognized that the end of Earth's seasonal cycle was also the starting point of a new year and a time for dormancy. They closed the passes at the Solstice to enforce a rest from commerce and activity. The ruler herself did not travel. You have passed this way before but you are not regressing. This is progress, for the cycle now repeats itself, and this time you are aware that it truly is a cycle. The return of old familiars is welcome. You can be as sure of this cycle as you are that seven days bring the start of a new week. Use this dormancy phase to plan which direction you will grow.",
  },
  {
    number: 25,
    names: ['Without Embroiling', 'Innocence (The Unexpected)'],
    chineseName: '無妄',
    pinyinName: 'wú wàng',
    character: '䷘',
    topTrigram: 1,
    bottomTrigram: 3,
    binary: '111001',
    linesString: '100111',
    lines: [1, 0, 0, 1, 1, 1],
    description:
      'Thunder rolls beneath Heaven, as is its nature and place: Sage rulers aligned themselves with the changing seasons, nurturing and guiding their subjects to do the same. Exceptional progress if you are mindful to keep out of the way of the natural Flow. It would be a fatal error to try to alter its course. This is a time of Being, not Doing.',
  },
  {
    number: 26,
    names: ['Great Accumulating', 'The Taming Power of the Great'],
    chineseName: '大畜',
    pinyinName: 'dà chù',
    character: '䷙',
    topTrigram: 5,
    bottomTrigram: 1,
    binary: '100111',
    linesString: '111001',
    lines: [1, 1, 1, 0, 0, 1],
    description:
      "Heaven's motherlode waits within the Mountain: The Superior Person mines deep into history's wealth of wisdom and deeds, charging her character with timeless strength. Persevere. Drawing sustenance from these sources creates good fortune. Then you may cross to the far shore.",
  },
  {
    number: 27,
    names: ['Swallowing', 'The Corners of the Mouth (Providing Nourishment)'],
    chineseName: '頤',
    pinyinName: 'yí',
    character: '䷚',
    topTrigram: 5,
    bottomTrigram: 3,
    binary: '100001',
    linesString: '100001',
    lines: [1, 0, 0, 0, 0, 1],
    description:
      'Beneath the immobile Mountain the arousing Thunder stirs: The Superior Person preserves her freedom under oppressive conditions by watching what comes out of her mouth, as well as what goes in. Endure and good fortune will come. Nurture others in need, as if you were feeding yourself. Take care not to provide sustenance for those who feed off others. Stay as high as possible on the food chain.',
  },
  {
    number: 28,
    names: ['Great Exceeding', 'Preponderance of the Great'],
    chineseName: '大過',
    pinyinName: 'dà guò',
    character: '䷛',
    topTrigram: 8,
    bottomTrigram: 6,
    binary: '011110',
    linesString: '011110',
    lines: [0, 1, 1, 1, 1, 0],
    description:
      'The Flood rises above the tallest Tree: Amidst a rising tide of human folly, the Superior Person retires to higher ground, renouncing her world without looking back. Any direction is better than where you now stand.',
  },
  {
    number: 29,
    names: ['Gorge', 'The Abysmal (Water)'],
    chineseName: '坎',
    pinyinName: 'kǎn',
    character: '䷜',
    topTrigram: 4,
    bottomTrigram: 4,
    binary: '010010',
    linesString: '010010',
    lines: [0, 1, 0, 0, 1, 0],
    description:
      'Water follows Water, spilling over any cliff, flowing past all obstacles, no matter the depth or distance, to the sea. The Superior Person learns flexibility from the mistakes she has made, and grows strong from the obstacles she has overcome, pressing on to show others the Way.',
  },
  {
    number: 30,
    names: ['Radiance', 'The Clinging, Fire'],
    chineseName: '離',
    pinyinName: 'lí',
    character: '䷝',
    topTrigram: 7,
    bottomTrigram: 7,
    binary: '101101',
    linesString: '101101',
    lines: [1, 0, 1, 1, 0, 1],
    description:
      'Fire sparks more Flames: The Superior Person holds an inner Fire that ignites passion in every heart it touches, until all the world is enlightened and aflame. With so searing a flame, success will not be denied you. Take care to be as peaceful and nurturing as the cow in the meadow; you are strong enough to be gentle.',
  },
  {
    number: 31,
    names: ['Conjoining', 'Influence (Wooing)'],
    chineseName: '咸',
    pinyinName: 'xián',
    character: '䷞',
    topTrigram: 8,
    bottomTrigram: 5,
    binary: '011100',
    linesString: '001110',
    lines: [0, 0, 1, 1, 1, 0],
    description:
      'The joyous Lake is cradled by the tranquil Mountain: The Superior Person takes great satisfaction in encouraging others along their journey. She draws them to her with her welcoming nature and genuine interest. Supreme success. This course leads to marriage.',
  },
  {
    number: 32,
    names: ['Persevering', 'Duration'],
    chineseName: '恆',
    pinyinName: 'héng',
    character: '䷟',
    topTrigram: 3,
    bottomTrigram: 6,
    binary: '001110',
    linesString: '011100',
    lines: [0, 1, 1, 1, 0, 0],
    description:
      'Arousing Thunder and penetrating Wind, close companions in any storm: The Superior Person possesses a resiliency and durability that lets her remain firmly and faithfully on course. Such constancy deserves success.',
  },
  {
    number: 33,
    names: ['Retiring', 'Retreat'],
    chineseName: '遯',
    pinyinName: 'dùn',
    character: '䷠',
    topTrigram: 1,
    bottomTrigram: 5,
    binary: '111100',
    linesString: '001111',
    lines: [0, 0, 1, 1, 1, 1],
    description:
      'The tranquil Mountain towers overhead, yet remains this side of Heaven: The Superior Person avoids the petty and superficial by keeping shallow men at a distance, not in anger but with dignity. Such a retreat sweeps the path clear to Success. Occupy yourself with minute detail.',
  },
  {
    number: 34,
    names: ['Great Invigorating', 'The Power of the Great'],
    chineseName: '大壯',
    pinyinName: 'dà zhuàng',
    character: '䷡',
    topTrigram: 3,
    bottomTrigram: 1,
    binary: '001111',
    linesString: '111100',
    lines: [1, 1, 1, 1, 0, 0],
    description:
      'Thunder fills the Heavens with its awful roar, not out of pride, but with integrity; if it did less, it would not be Thunder: Because of her Great Power, the Superior Person takes pains not to overstep her position, so that she will not seem intimidating or threatening to the Established Order. Opportunity will arise along this course.',
  },
  {
    number: 35,
    names: ['Prospering', 'Progress'],
    chineseName: '晉',
    pinyinName: 'jìn',
    character: '䷢',
    topTrigram: 7,
    bottomTrigram: 2,
    binary: '101000',
    linesString: '000101',
    lines: [0, 0, 0, 1, 0, 1],
    description:
      'The Sun shines down upon the Earth: Constantly honing and refining her brilliance, the Superior Person is a Godsend to her people. They repay her benevolence with a herd of horses, and she is granted audience three times in a single day. Promotion.',
  },
  {
    number: 36,
    names: ['Darkening of the Light'],
    chineseName: '明夷',
    pinyinName: 'míng yí',
    character: '䷣',
    topTrigram: 2,
    bottomTrigram: 7,
    binary: '000101',
    linesString: '101000',
    lines: [1, 0, 1, 0, 0, 0],
    description:
      'Warmth and Light are swallowed by deep Darkness: The Superior Person shows her brilliance by keeping it veiled among the masses. Stay true to your course, despite the visible obstacles ahead.',
  },
  {
    number: 37,
    names: ['Dwelling People', 'The Family [The Clan]'],
    chineseName: '家人',
    pinyinName: 'jiā rén',
    character: '䷤',
    topTrigram: 6,
    bottomTrigram: 7,
    binary: '110101',
    linesString: '101011',
    lines: [1, 0, 1, 0, 1, 1],
    description:
      'Warming Air Currents rise and spread from the Hearthfire: The Superior Person weighs her words carefully and is consistent in her behavior. Be as faithful as a good wife.',
  },
  {
    number: 38,
    names: ['Polarizing', 'Opposition'],
    chineseName: '睽',
    pinyinName: 'kuí',
    character: '䷥',
    topTrigram: 7,
    bottomTrigram: 8,
    binary: '101011',
    linesString: '110101',
    lines: [1, 1, 0, 1, 0, 1],
    description:
      'Fire distances itself from its nemesis, the Lake: No matter how large or diverse the group, the Superior Person remains uniquely herself. Small accomplishments are possible.',
  },
  {
    number: 39,
    names: ['Limping', 'Obstruction'],
    chineseName: '蹇',
    pinyinName: 'jiǎn',
    character: '䷦',
    topTrigram: 4,
    bottomTrigram: 5,
    binary: '010100',
    linesString: '001010',
    lines: [0, 0, 1, 0, 1, 0],
    description:
      'Ominous roiling in the Crater Lake atop the Volcano: When meeting an impasse, the Superior Person turns her gaze within, and views the obstacle from a new perspective. Offer your opponent nothing to resist. Let a sage guide you in this. Good fortune lies along this course.',
  },
  {
    number: 40,
    names: ['Taking-Apart', 'Deliverance'],
    chineseName: '解',
    pinyinName: 'xiè',
    character: '䷧',
    topTrigram: 3,
    bottomTrigram: 4,
    binary: '001010',
    linesString: '010100',
    lines: [0, 1, 0, 1, 0, 0],
    description:
      'A Thunderous Cloudburst shatters the oppressive humidity: The Superior Person knows the release in forgiveness, pardoning the faults of others and dealing gently with those who sin against her. It pays to accept things as they are for now. If there is nothing else to be gained, a return brings good fortune. If there is something yet to be gained, act on it at once.',
  },
  {
    number: 41,
    names: ['Diminishing', 'Decrease'],
    chineseName: '損',
    pinyinName: 'sǔn',
    character: '䷨',
    topTrigram: 5,
    bottomTrigram: 8,
    binary: '100011',
    linesString: '110001',
    lines: [1, 1, 0, 0, 0, 1],
    description:
      'The stoic Mountain drains its excess waters to the Lake below: The Superior Person curbs her anger and sheds her desires. To be frugal and content is to possess immeasurable wealth within. Nothing of value could be refused such a person. Make a portion of each meal a share of your offering.',
  },
  {
    number: 42,
    names: ['Augmenting', 'Increase'],
    chineseName: '益',
    pinyinName: 'yì',
    character: '䷩',
    topTrigram: 6,
    bottomTrigram: 3,
    binary: '110001',
    linesString: '100011',
    lines: [1, 0, 0, 0, 1, 1],
    description:
      'Whirlwinds and Thunder: When the Superior Person encounters saintly behavior, she adopts it; when she encounters a fault within, she transforms it. Progress in every endeavor. You may cross to the far shore.',
  },
  {
    number: 43,
    names: ['Displacement', 'Break-through (Resoluteness)'],
    chineseName: '夬',
    pinyinName: 'guài',
    character: '䷪',
    topTrigram: 8,
    bottomTrigram: 1,
    binary: '011111',
    linesString: '111110',
    lines: [1, 1, 1, 1, 1, 0],
    description:
      'A Deluge from Heaven: The Superior Person rains fortune upon those in need, then moves on with no thought of the good she does. The issue must be raised before an impartial authority. Be sincere and earnest, despite the danger. Do not try to force the outcome, but seek support where needed. Set a clear goal.',
  },
  {
    number: 44,
    names: ['Coupling', 'Coming to Meet'],
    chineseName: '姤',
    pinyinName: 'gòu',
    character: '䷫',
    topTrigram: 1,
    bottomTrigram: 6,
    binary: '111110',
    linesString: '011111',
    lines: [0, 1, 1, 1, 1, 1],
    description:
      'A playful Zephyr dances and delights beneath indulgent Heaven: A Prince who shouts orders but will not walk among her people may as well try to command the four winds. A strong, addictive temptation, much more dangerous than it seems.',
  },
  {
    number: 45,
    names: ['Clustering', 'Gathering Together [Massing]'],
    chineseName: '萃',
    pinyinName: 'cuì',
    character: '䷬',
    topTrigram: 8,
    bottomTrigram: 2,
    binary: '011000',
    linesString: '000110',
    lines: [0, 0, 0, 1, 1, 0],
    description:
      "The Lake rises by welcoming and receiving Earth's waters: The King approaches her temple. It is wise to seek audience with her there. Success follows this course. Making an offering will seal your good fortune. A goal will be realized now.",
  },
  {
    number: 46,
    names: ['Ascending', 'Pushing Upward'],
    chineseName: '升',
    pinyinName: 'shēng',
    character: '䷭',
    topTrigram: 2,
    bottomTrigram: 6,
    binary: '000110',
    linesString: '011000',
    lines: [0, 1, 1, 0, 0, 0],
    description:
      'Beneath the Soil, the Seedling pushes upward toward the light: To preserve her integrity, the Superior Person contents herself with small gains that eventually lead to great accomplishment. Supreme success. Have no doubts. Seek guidance from someone you respect. A constant move toward greater clarity will bring reward.',
  },
  {
    number: 47,
    names: ['Confining', 'Oppression (Exhaustion)'],
    chineseName: '困',
    pinyinName: 'kùn',
    character: '䷮',
    topTrigram: 8,
    bottomTrigram: 4,
    binary: '011010',
    linesString: '010110',
    lines: [0, 1, 0, 1, 1, 0],
    description:
      'A Dead Sea, its Waters spent eons ago, more deadly than the desert surrounding it: The Superior Person will stake her life and fortune on what she deeply believes. Triumph belongs to those who endure. Trial and tribulation can hone exceptional character to a razor edge that slices deftly through every challenge. Action prevails where words will fail.',
  },
  {
    number: 48,
    names: ['Welling', 'The Well'],
    chineseName: '井',
    pinyinName: 'jǐng',
    character: '䷯',
    topTrigram: 4,
    bottomTrigram: 6,
    binary: '010110',
    linesString: '011010',
    lines: [0, 1, 1, 0, 1, 0],
    description:
      'Deep Waters Penetrated and drawn to the surface: The Superior Person refreshes the people with constant encouragement to help one another. Encampments, settlements, walled cities, whole empires may rise and fall, yet the Well at the center endures, never drying to dust, never overflowing. It served those before and will serve those after. Again and again you may draw from the Well, but if the bucket breaks or the rope is too short there will be misfortune.',
  },
  {
    number: 49,
    names: ['Skinning', 'Revolution (Molting)'],
    chineseName: '革',
    pinyinName: 'gé',
    character: '䷰',
    topTrigram: 8,
    bottomTrigram: 7,
    binary: '011101',
    linesString: '101110',
    lines: [1, 0, 1, 1, 1, 0],
    description:
      'Fire ignites within the Lake, defying conditions that would deny it birth or survival: The Superior Person reads the Signs of the Times and makes the Season apparent to all. The support you need will come only after the deed is done. Renewed forces, however, will provide fresh energy for exceptional progress. Persevere. All differences vanish.',
  },
  {
    number: 50,
    names: ['Holding', 'The Caldron'],
    chineseName: '鼎',
    pinyinName: 'dǐng',
    character: '䷱',
    topTrigram: 7,
    bottomTrigram: 6,
    binary: '101110',
    linesString: '011101',
    lines: [0, 1, 1, 1, 0, 1],
    description:
      'Fire rises hot and bright from the Wood beneath the sacrificial caldron: The Superior Person positions herself correctly within the flow of Cosmic forces. Supreme accomplishment.',
  },
  {
    number: 51,
    names: ['Shake', 'The Arousing (Shock, Thunder)'],
    chineseName: '震',
    pinyinName: 'zhèn',
    character: '䷲',
    topTrigram: 3,
    bottomTrigram: 3,
    binary: '001001',
    linesString: '100100',
    lines: [1, 0, 0, 1, 0, 0],
    description:
      "Thunder echoes upon Thunder, commanding reverence for its father Heaven: In awe of Heaven's majestic power, the Superior Person looks within and sets her life in order. Thunder mingles with startled screams of terror for a hundred miles around. As the people nervously laugh at their own fright, the devout presents the sacrificial chalice with nary a drop of wine spilt. Deliverance.",
  },
  {
    number: 52,
    names: ['Bound', 'Keeping Still, Mountain'],
    chineseName: '艮',
    pinyinName: 'gèn',
    character: '䷳',
    topTrigram: 5,
    bottomTrigram: 5,
    binary: '100100',
    linesString: '001001',
    lines: [0, 0, 1, 0, 0, 1],
    description:
      "Above this Mountain's summit another more majestic rises: The Superior Person is mindful to keep her thoughts in the here and now. Stilling the sensations of the Ego, she roams her courtyard without moving a muscle, unencumbered by the fears and desires of her fellows. This is no mistake.",
  },
  {
    number: 53,
    names: ['Infiltrating', 'Development (Gradual Progress)'],
    chineseName: '漸',
    pinyinName: 'jiàn',
    character: '䷴',
    topTrigram: 6,
    bottomTrigram: 5,
    binary: '110100',
    linesString: '001011',
    lines: [0, 0, 1, 0, 1, 1],
    description:
      'The gnarled Pine grows tenaciously off the Cliff face: The Superior Person clings faithfully to dignity and integrity, thus elevating the Collective Spirit of Person in her own small way. Development. The maiden is given in marriage. Good fortune if you stay on course.',
  },
  {
    number: 54,
    names: ['Converting the Maiden', 'The Marrying Maiden'],
    chineseName: '歸妹',
    pinyinName: 'guī mèi',
    character: '䷵',
    topTrigram: 3,
    bottomTrigram: 8,
    binary: '001011',
    linesString: '110100',
    lines: [1, 1, 0, 1, 0, 0],
    description:
      'The Thunderstorm inseminates the swelling Lake, then moves on where the Lake cannot follow: The Superior Person views passing trials in the light of Eternal Truths. Any action will prove unfortunate. Nothing furthers.',
  },
  {
    number: 55,
    names: ['Abouding', 'Abundance [Fullness]'],
    chineseName: '豐',
    pinyinName: 'fēng',
    character: '䷶',
    topTrigram: 3,
    bottomTrigram: 7,
    binary: '001101',
    linesString: '101100',
    lines: [1, 0, 1, 1, 0, 0],
    description:
      "Thunder and Lightning from the dark heart of the storm: The Superior Person judges fairly, so that consequences are just. The leader reaches her peak and doesn't lament the descent before her. Be like the noonday sun at its zenith. This is success.",
  },
  {
    number: 56,
    names: ['Sojourning', 'The Wanderer'],
    chineseName: '旅',
    pinyinName: 'lǚ',
    character: '䷷',
    topTrigram: 7,
    bottomTrigram: 5,
    binary: '101100',
    linesString: '001101',
    lines: [0, 0, 1, 1, 0, 1],
    description:
      'Fire on the Mountain, catastrophic to man, a passing annoyance to the Mountain: The Superior Person waits for wisdom and clarity before exacting Justice, then lets no protest sway her. Find satisfaction in small gains. To move constantly forward is good fortune to a Wanderer.',
  },
  {
    number: 57,
    names: ['Ground', 'The Gentle (The Penetrating, Wind)'],
    chineseName: '巽',
    pinyinName: 'xùn',
    character: '䷸',
    topTrigram: 6,
    bottomTrigram: 6,
    binary: '110110',
    linesString: '011011',
    lines: [0, 1, 1, 0, 1, 1],
    description:
      'Wind follows upon wind, wandering the earth, penetrating gently but persistently: The Superior Person expands her influence by reaffirming her decisions and carrying out her promises. Small, persistent, focused effort brings success. Seek advice from someone you respect.',
  },
  {
    number: 58,
    names: ['Open', 'The Joyous, Lake'],
    chineseName: '兌',
    pinyinName: 'duì',
    character: '䷹',
    topTrigram: 8,
    bottomTrigram: 8,
    binary: '011011',
    linesString: '110110',
    lines: [1, 1, 0, 1, 1, 0],
    description:
      'The joyous Lake spans on and on to the horizon: The Superior Person renews and expands her Spirit through heart-to-heart exchanges with others. Success if you stay on course.',
  },
  {
    number: 59,
    names: ['Dispersing', 'Dispersion [Dissolution]'],
    chineseName: '渙',
    pinyinName: 'huàn',
    character: '䷺',
    topTrigram: 6,
    bottomTrigram: 4,
    binary: '110010',
    linesString: '010011',
    lines: [0, 1, 0, 0, 1, 1],
    description:
      'Wind carries the Mists aloft: Sage rulers dedicated their lives to serving a Higher Power and built temples that still endure. The King approaches her temple. Success if you stay on course. You may cross to the far shore.',
  },
  {
    number: 60,
    names: ['Articulating', 'Limitation'],
    chineseName: '節',
    pinyinName: 'jié',
    character: '䷻',
    topTrigram: 4,
    bottomTrigram: 8,
    binary: '010011',
    linesString: '110010',
    lines: [1, 1, 0, 0, 1, 0],
    description:
      "Waters difficult to keep within the Lake's banks: The Superior Person examines the nature of virtue and makes herself a standard that can be followed. Self-discipline brings success; but restraints too binding bring self-defeat.",
  },
  {
    number: 61,
    names: ['Center Returing', 'Inner Truth'],
    chineseName: '中孚',
    pinyinName: 'zhōng fú',
    character: '䷼',
    topTrigram: 6,
    bottomTrigram: 8,
    binary: '110011',
    linesString: '110011',
    lines: [1, 1, 0, 0, 1, 1],
    description:
      "The gentle Wind ripples the Lake's surface: The Superior Person finds common ground between points of contention, wearing away rigid perspectives that would lead to fatal error. Pigs and fishes. You may cross to the far shore. Great fortune if you stay on course.",
  },
  {
    number: 62,
    names: ['Small Exceeding', 'Preponderance of the Small'],
    chineseName: '小過',
    pinyinName: 'xiǎo guò',
    character: '䷽',
    topTrigram: 3,
    bottomTrigram: 5,
    binary: '001100',
    linesString: '001100',
    lines: [0, 0, 1, 1, 0, 0],
    description:
      'Thunder high on the Mountain, active passivity: The Superior Person is unsurpassed in her ability to remain small. In a time for humility, she is supremely modest. In a time of mourning, she uplifts with somber reverence. In a time of want, she is resourcefully frugal. When a bird flies too high, its song is lost. Rather than push upward now, it is best to remain below. This will bring surprising good fortune, if you keep to your course.',
  },
  {
    number: 63,
    names: ['Already Fording', 'After Completion'],
    chineseName: '既濟',
    pinyinName: 'jì jì',
    character: '䷾',
    topTrigram: 4,
    bottomTrigram: 7,
    binary: '010101',
    linesString: '101010',
    lines: [1, 0, 1, 0, 1, 0],
    description:
      'Boiling Water over open Flame, one might extinguish the other: The Superior Person takes a 360 degree view of the situation and prepares for any contingency. Success in small matters if you stay on course. Early good fortune can end in disorder.',
  },
  {
    number: 64,
    names: ['Not Yet Fording', 'Before Completion'],
    chineseName: '未濟',
    pinyinName: 'wèi jì',
    character: '䷿',
    topTrigram: 7,
    bottomTrigram: 4,
    binary: '101010',
    linesString: '010101',
    lines: [0, 1, 0, 1, 0, 1],
    description:
      'Fire ascends above the Water: The Superior Person examines the nature of things and keeps each in its proper place. Too anxious the young fox gets her tail wet, just as she completes her crossing. To attain success, be like the woman and not like the fox.',
  },
];
